version: "3.8"
volumes:
  webvol:
  clientvol:

services:
  web:
    image: tracks-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - webvol:/web
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: tracks-web
    working_dir: /web
    command: python manage.py migrate --noinput
    volumes:
      - webvol:/web
  client:
    build:
      context: ./tracks-svr
      dockerfile: Dockerfile
    image: tracks-ui
    working_dir: /ui
    command: npm start
    volumes:
      - clientvol:/ui
    ports:
      - "3000:3000"

