version: "3"

services:
  web:
    image: tracks-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/web
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: tracks-web
    working_dir: /web
    command: python manage.py migrate --noinput
    volumes:
      - ./app:/web
  client:
    build:
      context: ./tracks-svr
      dockerfile: Dockerfile    
    image: tracks-ui
    working_dir: /ui
    command: npm start
    volumes:
      - ./tracks-svr:/ui
    ports:
      - "3000:3000"
    # depends_on:
    #   - client_env
  # client_env:
  #   image: tracks-ui
  #   working_dir: /ui
  #   command: npm install
  #   volumes:
  #     - ./tracks-svr:/ui
