version: "3"

services:
  web:
    image: tracks-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/web
    ports:
      - "8000:8000"
    depends_on:
      - migration
  migration:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: tracks-web
    working_dir: /web
    command: python manage.py migrate --noinput
    volumes:
      - ./app:/web
  client:
    image: tracks-web
    command: ps -ef
    depends_on:
      - web
